from qbuild import O, F, E

NONE = "아무것도 출력되지 않음"

조건문 = {
 "square": [
  O("if x > 5:", "x = 7\nif x > 5:\n    print('big')", "big", ["small", "7", NONE], "x=7은 5보다 크므로 if 안이 실행됩니다."),
  O("else:", "x = 3\nif x > 5:\n    print('big')\nelse:\n    print('small')", "small", ["big", "3", "오류"], "if 조건이 거짓이면 else가 실행됩니다."),
  O("elif x == 3:", "x = 3\nif x > 5:\n    print('A')\nelif x == 3:\n    print('B')", "B", ["A", "A B", NONE], "첫 조건이 거짓이면 elif 조건을 검사합니다."),
  F("if x == 10:", "빈칸에 들어갈 연산자는? if x ___ 10:  (x가 10과 같은지 검사)", "==", ["=", "!=", "=>"], "같은지 비교할 때는 == 를 씁니다."),
  O("if not done:", "done = False\nif not done:\n    print('go')", "go", ["stop", "False", NONE], "not False는 True라서 실행됩니다."),
  O("if x % 2 == 0:", "x = 4\nif x % 2 == 0:\n    print('even')\nelse:\n    print('odd')", "even", ["odd", "0", "오류"], "4를 2로 나눈 나머지가 0이면 짝수입니다."),
  O("if name == 'Kim':", "name = 'Lee'\nif name == 'Kim':\n    print('Hi Kim')\nelse:\n    print('Who?')", "Who?", ["Hi Kim", "Lee", "오류"], "'Lee'는 'Kim'과 달라서 else가 실행됩니다."),
  O("if x >= 10:", "x = 10\nif x >= 10:\n    print('ok')", "ok", ["no", "10", NONE], ">= 는 같을 때도 참입니다."),
  O("if x != 0:", "x = 0\nif x != 0:\n    print('nonzero')\nelse:\n    print('zero')", "zero", ["nonzero", "0", "오류"], "x가 0이므로 != 0 은 거짓입니다."),
  E("if x < 5:", "if 1 < 5 print(1)", ["if True: print(1)", "if 1 < 5: print(1)", "if 'a': print(1)"], "if 조건 뒤에는 콜론(:)이 필요합니다."),
 ],
 "pyramid": [
  O("if x > 0 and x < 10:", "x = 5\nif x > 0 and x < 10:\n    print('in')\nelse:\n    print('out')", "in", ["out", "5", "오류"], "and는 두 조건이 모두 참이어야 합니다."),
  O("if x < 0 or x > 100:", "x = 50\nif x < 0 or x > 100:\n    print('bad')\nelse:\n    print('good')", "good", ["bad", "50", "오류"], "or는 하나라도 참이면 참인데, 둘 다 거짓입니다."),
  O("if x in [1, 2, 3]:", "x = 2\nif x in [1, 2, 3]:\n    print('yes')\nelse:\n    print('no')", "yes", ["no", "2", "오류"], "in은 포함 여부를 검사합니다."),
  O("elif score >= 80:", "score = 85\nif score >= 90:\n    print('A')\nelif score >= 80:\n    print('B')\nelse:\n    print('C')", "B", ["A", "C", "A B"], "85는 90 미만이고 80 이상입니다."),
  O("if x:", "x = 0\nif x:\n    print('T')\nelse:\n    print('F')", "F", ["T", "0", "오류"], "0은 거짓으로 취급됩니다."),
  O("if not s:", "s = ''\nif not s:\n    print('empty')", "empty", ["''", "not empty", NONE], "빈 문자열은 거짓이라 not s는 참입니다."),
  O("if 1 < x < 5:", "x = 3\nif 1 < x < 5:\n    print('mid')\nelse:\n    print('edge')", "mid", ["edge", "3", "오류"], "비교 연산자를 이어서 범위를 검사합니다."),
  O("if a > b: print(a)", "a, b = 2, 9\nif a > b: print(a)\nelse: print(b)", "9", ["2", "a", "오류"], "a가 b보다 크지 않으므로 else가 실행됩니다."),
  E("if x == 1:", "if True:\nprint(1)", ["if True:\n    print(1)", "if 0:\n    pass\nelse:\n    print(1)", "x = 1\nif x == 1:\n    pass"], "if 안의 코드는 들여쓰기해야 합니다."),
  O("if x > 5 and y > 5:", "x, y = 6, 3\nif x > 5 and y > 5:\n    print('both')\nelif x > 5 or y > 5:\n    print('one')", "one", ["both", "6", NONE], "둘 다는 아니고 하나만 참입니다."),
 ],
 "circle": [
  O("if x > 5 and not y:", "x, y = 7, 0\nif x > 5 and not y:\n    print('A')\nelse:\n    print('B')", "A", ["B", "7", "오류"], "not 0 은 True라서 두 조건이 모두 참입니다."),
  O("print('ok') if x else print('no')", "x = []\nprint('ok') if x else print('no')", "no", ["ok", "[]", "오류"], "빈 리스트는 거짓입니다."),
  O("r = 'a' if x > 0 else 'b' if x < 0 else 'c'", "x = -2\nr = 'a' if x > 0 else 'b' if x < 0 else 'c'\nprint(r)", "b", ["a", "c", "오류"], "삼항 연산을 이어 쓰면 차례로 검사합니다."),
  O("if x > 0:", "x = 5\nif x > 0:\n    if x > 10:\n        print('A')\n    else:\n        print('B')", "B", ["A", "A B", NONE], "바깥 if는 참이고, 안쪽 if는 거짓이라 else가 실행됩니다."),
  O("if x is None:", "x = None\nif x is None:\n    print('none')\nelse:\n    print('has')", "none", ["has", "None", "오류"], "None 비교에는 is를 씁니다."),
  O("if (x := 5) > 3:", "if (x := 5) > 3:\n    print(x)", "5", ["3", "True", "오류"], ":= 로 저장한 값이 조건 뒤에서도 쓰입니다."),
  O("if not (a or b):", "a, b = 0, 0\nif not (a or b):\n    print('both false')", "both false", [NONE, "오류", "a or b"], "a or b는 거짓이므로 not으로 참이 됩니다."),
  O("if x % 3 == 0 and x % 5 == 0:", "x = 15\nif x % 3 == 0 and x % 5 == 0:\n    print('FizzBuzz')\nelif x % 3 == 0:\n    print('Fizz')", "FizzBuzz", ["Fizz", "Buzz", "15"], "첫 조건이 먼저 참이라 FizzBuzz만 출력됩니다."),
  O("if any([0, 1, 0]):", "if any([0, 1, 0]):\n    print('yes')\nelse:\n    print('no')", "yes", ["no", "1", "오류"], "any는 하나라도 참이면 True입니다."),
  O("if all([1, 0, 1]):", "if all([1, 0, 1]):\n    print('yes')\nelse:\n    print('no')", "no", ["yes", "0", "오류"], "all은 모두 참이어야 True입니다."),
 ],
}

반복문 = {
 "square": [
  O("for i in range(3):", "for i in range(3):\n    print(i)", "0 1 2", ["1 2 3", "0 1 2 3", "1 2"], "range(3)은 0, 1, 2입니다."),
  O("for c in 'abc':", "for c in 'abc':\n    print(c)", "a b c", ["abc", "'a' 'b' 'c'", "오류"], "문자열은 글자를 하나씩 꺼냅니다."),
  O("while n > 0:", "n = 3\nwhile n > 0:\n    print(n)\n    n -= 1", "3 2 1", ["3 2 1 0", "2 1 0", "1 2 3"], "n이 0이 되면 조건이 거짓이 되어 멈춥니다."),
  O("break", "for i in range(5):\n    if i == 2:\n        break\n    print(i)", "0 1", ["0 1 2", "2", "0 1 2 3 4"], "break는 반복을 즉시 끝냅니다."),
  O("continue", "for i in range(4):\n    if i == 2:\n        continue\n    print(i)", "0 1 3", ["0 1", "0 1 2 3", "1 3"], "continue는 이번 차례만 건너뜁니다."),
  O("for i in range(1, 4):", "for i in range(1, 4):\n    print(i)", "1 2 3", ["1 2 3 4", "0 1 2 3", "2 3 4"], "range(1, 4)는 1부터 3까지입니다."),
  O("for i in range(2):", "for i in range(2):\n    print('hi')", "hi hi", ["hi", "hi hi hi", "0 1"], "두 번 반복해서 hi가 두 번 출력됩니다."),
  O("for i in [10, 20]:", "for i in [10, 20]:\n    print(i)", "10 20", ["0 1", "10", "20 10"], "리스트의 값을 차례로 꺼냅니다."),
  O("for i in range(0, 6, 2):", "for i in range(0, 6, 2):\n    print(i)", "0 2 4", ["0 2 4 6", "0 1 2 3 4 5", "2 4"], "세 번째 값은 증가 폭입니다."),
  F("while True:", "무한히 반복하려면 빈칸에 무엇을 써야 할까? while ____:", "True", ["False", "0", "None"], "조건이 항상 참이면 break 전까지 계속 반복됩니다."),
 ],
 "pyramid": [
  O("for i in range(3, 0, -1):", "for i in range(3, 0, -1):\n    print(i)", "3 2 1", ["3 2 1 0", "2 1 0", "1 2 3"], "증가 폭이 -1이면 거꾸로 세며 끝 값은 포함하지 않습니다."),
  O("for i, c in enumerate('ab'):", "for i, c in enumerate('ab'):\n    print(i, c)", "0 a 1 b", ["a 0 b 1", "1 a 2 b", "0 1 a b"], "enumerate는 (번호, 값)을 함께 줍니다."),
  O("total += i", "total = 0\nfor i in range(4):\n    total += i\nprint(total)", "6", ["10", "4", "3"], "0+1+2+3 = 6 입니다."),
  O("for i in range(2): print(i)", "for i in range(2): print(i)", "0 1", ["1 2", "0 1 2", "01"], "한 줄로 쓴 for문도 같은 방식으로 동작합니다."),
  O("while n < 3:", "n = 0\nwhile n < 3:\n    n += 1\nprint(n)", "3", ["2", "0", "4"], "n이 3이 되면 조건이 거짓이 되어 멈춥니다."),
  O("for x in 'ab':", "for x in 'ab':\n    for y in '12':\n        print(x + y)", "a1 a2 b1 b2", ["a1 b1 a2 b2", "ab 12", "a1 b2"], "바깥 반복 한 번마다 안쪽 반복이 전부 돕니다."),
  E("while i < 3:", "while i < 3\n    i += 1", ["i = 0\nwhile i < 3:\n    i += 1", "for i in range(3):\n    pass", "i = 5\nwhile i < 3:\n    pass"], "while 조건 뒤에도 콜론(:)이 필요합니다."),
  O("for i in range(10):", "for i in range(10):\n    if i % 4 == 0:\n        print(i)", "0 4 8", ["4 8", "0 4", "0 4 8 10"], "4로 나눈 나머지가 0인 값만 출력합니다."),
  O("for i in reversed(range(3)):", "for i in reversed(range(3)):\n    print(i)", "2 1 0", ["0 1 2", "3 2 1", "2 1"], "reversed는 순서를 뒤집습니다."),
  O("for k in {'a': 1, 'b': 2}:", "for k in {'a': 1, 'b': 2}:\n    print(k)", "a b", ["1 2", "a 1 b 2", "('a', 1)"], "딕셔너리를 반복하면 키가 나옵니다."),
 ],
 "circle": [
  O("for i in range(3): print(i * 2)", "for i in range(3): print(i * 2)", "0 2 4", ["0 1 2", "2 4 6", "0 2 4 6"], "i가 0, 1, 2일 때 2배 한 값이 출력됩니다."),
  O("[i * i for i in range(4)]", "print([i * i for i in range(4)])", "[0, 1, 4, 9]", ["[1, 4, 9, 16]", "[0, 1, 2, 3]", "[0, 2, 4, 6]"], "각 i의 제곱을 모아 리스트로 만듭니다."),
  O("for j in range(i):", "for i in range(4):\n    for j in range(i):\n        print('*', end='')\n    print()", "* ** ***", ["* ** *** ****", "*** ** *", "** ** **"], "i가 커질수록 별이 한 개씩 늘어납니다. i=0일 때는 빈 줄입니다."),
  O("while n:", "n = 3\nwhile n:\n    print(n)\n    n -= 1", "3 2 1", ["3 2 1 0", "오류", "무한 반복"], "n이 0이 되면 거짓이라 멈춥니다."),
  O("for a, b in zip([1, 2], 'xy'):", "for a, b in zip([1, 2], 'xy'):\n    print(a, b)", "1 x 2 y", ["1 2 x y", "x 1 y 2", "1 y 2 x"], "zip은 같은 위치의 값끼리 묶습니다."),
  O("for i in range(1, 10, 3):", "for i in range(1, 10, 3):\n    print(i)", "1 4 7", ["1 4 7 10", "1 3 5 7 9", "4 7"], "1에서 시작해 3씩 증가하며 10 미만입니다."),
  O("sum(i for i in range(5))", "print(sum(i for i in range(5)))", "10", ["15", "4", "5"], "0+1+2+3+4 = 10 입니다."),
  O("while n * n < 20:", "n = 0\nwhile n * n < 20:\n    n += 1\nprint(n)", "5", ["4", "20", "6"], "n=5일 때 25로 처음 20 이상이 되어 멈춥니다."),
  O("for _ in range(3):", "s = ''\nfor _ in range(3):\n    s += 'ab'\nprint(s)", "ababab", ["ab3", "abab", "ab ab ab"], "'ab'를 세 번 이어 붙입니다."),
  O("list(range(5, 0, -2))", "print(list(range(5, 0, -2)))", "[5, 3, 1]", ["[5, 3, 1, -1]", "[4, 2]", "[5, 4, 3, 2, 1]"], "5에서 2씩 줄어들며 0보다 큰 동안입니다."),
 ],
}

함수 = {
 "square": [
  O("def hi():", "def hi():\n    print('hi')\nhi()", "hi", [NONE, "hi()", "오류"], "정의 후 호출해야 실행됩니다."),
  O("def add(a, b):", "def add(a, b):\n    return a + b\nprint(add(1, 2))", "3", ["12", "None", "오류"], "return 값이 호출한 곳으로 돌아옵니다."),
  O("return a * 2", "def f(a):\n    return a * 2\nprint(f(4))", "8", ["44", "None", "4"], "인수 4에 2를 곱한 8을 돌려줍니다."),
  O("def hello(name):", "def hello(name):\n    print('Hi', name)\nhello('Kim')", "Hi Kim", ["Hi name", "Hi", "오류"], "매개변수 name에 'Kim'이 전달됩니다."),
  O("print(square(3))", "def square(n):\n    return n * n\nprint(square(3))", "9", ["6", "33", "None"], "3 * 3 = 9 를 돌려줍니다."),
  O("def nothing():", "def nothing():\n    pass\nprint(nothing())", "None", ["0", "pass", "오류"], "return이 없는 함수는 None을 돌려줍니다."),
  F("def f(x):", "함수를 정의할 때 쓰는 키워드는? ___ f(x):", "def", ["func", "function", "define"], "함수는 def로 정의합니다."),
  O("def greet(n='Kim'):", "def greet(n='Kim'):\n    print(n)\ngreet()", "Kim", ["n", NONE, "오류"], "인수를 주지 않으면 기본값이 쓰입니다."),
  O("lambda x: x + 1", "f = lambda x: x + 1\nprint(f(1))", "2", ["1", "x + 1", "오류"], "lambda는 이름 없는 짧은 함수입니다."),
  O("max(3, 7)", "print(max(3, 7))", "7", ["3", "10", "(3, 7)"], "max는 가장 큰 값을 돌려주는 내장 함수입니다."),
 ],
 "pyramid": [
  O("def area(w, h=2):", "def area(w, h=2):\n    return w * h\nprint(area(3))", "6", ["5", "3", "오류"], "h를 생략하면 기본값 2가 사용됩니다."),
  O("return a, b", "def f():\n    return 1, 2\nprint(f())", "(1, 2)", ["1 2", "[1, 2]", "1"], "여러 값을 돌려주면 튜플로 묶입니다."),
  O("def f(*args):", "def f(*args):\n    return len(args)\nprint(f(1, 2, 3))", "3", ["1", "6", "오류"], "*args는 남는 인수를 튜플로 모읍니다."),
  O("def f(**kw):", "def f(**kw):\n    return kw\nprint(f(a=1))", "{'a': 1}", ["a=1", "(1,)", "오류"], "**kw는 이름 붙은 인수를 딕셔너리로 모읍니다."),
  O("global count", "count = 0\ndef inc():\n    global count\n    count += 1\ninc()\nprint(count)", "1", ["0", "오류", "None"], "global을 쓰면 함수 안에서 바깥 변수를 바꿀 수 있습니다."),
  E("f(1, 2)", "def f(a):\n    return a\nf(1, 2)", ["def f(a):\n    return a\nf(1)", "def f(a, b=0):\n    return a\nf(1, 2)", "def f(*a):\n    return a\nf(1, 2)"], "인수 개수가 맞지 않으면 TypeError가 납니다."),
  O("def fact(n):", "def fact(n):\n    return 1 if n <= 1 else n * fact(n - 1)\nprint(fact(4))", "24", ["10", "12", "4"], "4 * 3 * 2 * 1 = 24 입니다."),
  O("f = lambda a, b: a * b", "f = lambda a, b: a * b\nprint(f(3, 4))", "12", ["7", "34", "오류"], "lambda에도 인수를 여러 개 받을 수 있습니다."),
  O("def f(a, b):", "def f(a, b):\n    return a - b\nprint(f(b=1, a=5))", "4", ["-4", "오류", "6"], "이름으로 전달하면 순서와 상관없이 a=5, b=1 입니다."),
  O("sorted([3, 1], key=lambda x: -x)", "print(sorted([3, 1], key=lambda x: -x))", "[3, 1]", ["[1, 3]", "[-3, -1]", "오류"], "key가 음수이므로 큰 값이 앞에 옵니다."),
 ],
 "circle": [
  O("def make(n):", "def make(n):\n    return lambda x: x + n\nadd2 = make(2)\nprint(add2(5))", "7", ["5", "2", "오류"], "안쪽 함수가 n=2를 기억합니다(클로저)."),
  O("def f(x, acc=[]):", "def f(x, acc=[]):\n    acc.append(x)\n    return acc\nf(1)\nprint(f(2))", "[1, 2]", ["[2]", "[1]", "[]"], "기본값 리스트는 호출 사이에 공유됩니다."),
  O("def fib(n):", "def fib(n):\n    return n if n < 2 else fib(n - 1) + fib(n - 2)\nprint(fib(6))", "8", ["13", "6", "5"], "피보나치 수열 0,1,1,2,3,5,8 입니다."),
  O("def gen():", "def gen():\n    yield 1\n    yield 2\nprint(list(gen()))", "[1, 2]", ["[1, 2, 3]", "1 2", "오류"], "yield로 값을 하나씩 만들어 냅니다."),
  O("def outer():", "def outer():\n    x = 1\n    def inner():\n        return x + 1\n    return inner()\nprint(outer())", "2", ["1", "오류", "None"], "안쪽 함수는 바깥 함수의 변수를 읽을 수 있습니다."),
  O("map(lambda x: x * 2, [1, 2])", "print(list(map(lambda x: x * 2, [1, 2])))", "[2, 4]", ["[1, 2]", "[2, 4, 6]", "map object"], "map은 각 원소에 함수를 적용합니다."),
  O("filter(lambda x: x > 1, [1, 2, 3])", "print(list(filter(lambda x: x > 1, [1, 2, 3])))", "[2, 3]", ["[1]", "[1, 2, 3]", "[True, True]"], "filter는 조건이 참인 원소만 남깁니다."),
  O("def f(n): return n * 2", "def f(n): return n * 2\nprint(f(f(2)))", "8", ["4", "6", "오류"], "f(2)=4, f(4)=8 입니다."),
  O("def f(a, b=1, *c):", "def f(a, b=1, *c):\n    return a, b, c\nprint(f(1, 2, 3, 4))", "(1, 2, (3, 4))", ["(1, 2, 3, 4)", "(1, 2, [3, 4])", "오류"], "남는 인수는 *c에 튜플로 담깁니다."),
  O("def deco(fn):", "def deco(fn):\n    return lambda: fn() + 1\n@deco\ndef f():\n    return 1\nprint(f())", "2", ["1", "오류", "None"], "데코레이터가 원래 결과에 1을 더하는 함수로 바꿉니다."),
 ],
}
