from qbuild import O, F, E

출력 = {
 "square": [
  O("print('Hello')", "print('Hello')", "Hello", ["'Hello'", "hello", "print Hello"], "print는 따옴표 없이 문자열 내용만 출력합니다."),
  O("print(3 + 4)", "print(3 + 4)", "7", ["34", "3 + 4", "오류"], "따옴표가 없으면 계산한 결과가 출력됩니다."),
  O("print('a', 'b')", "print('a', 'b')", "a b", ["ab", "a,b", "'a' 'b'"], "쉼표로 구분한 값은 공백을 사이에 두고 출력됩니다."),
  O("print('Hi' * 3)", "print('Hi' * 3)", "HiHiHi", ["Hi 3", "Hi*3", "오류"], "문자열에 정수를 곱하면 그만큼 반복됩니다."),
  F("print('Python')", "빈칸에 들어갈 함수 이름은? ____('Python') 로 화면에 글자를 출력한다.", "print", ["input", "output", "write"], "화면에 출력하는 함수는 print()입니다."),
  O("print(10 // 3)", "print(10 // 3)", "3", ["3.33", "4", "1"], "// 는 나눗셈의 몫만 구합니다."),
  O("print('A' + 'B')", "print('A' + 'B')", "AB", ["A B", "A+B", "오류"], "문자열끼리 + 하면 이어 붙입니다."),
  O("print(2 ** 3)", "print(2 ** 3)", "8", ["6", "9", "23"], "** 는 거듭제곱입니다. 2의 3제곱은 8입니다."),
  O("print('a', 'b', sep='-')", "print('a', 'b', sep='-')", "a-b", ["a b", "ab", "a - b"], "sep은 값 사이에 넣을 구분 문자를 정합니다."),
  O("print(len('abc'))", "print(len('abc'))", "3", ["2", "abc", "4"], "len은 글자 수를 셉니다."),
 ],
 "pyramid": [
  O("print('Name:', 'Kim')", "print('Name:', 'Kim')", "Name: Kim", ["Name:Kim", "Name: 'Kim'", "Name:, Kim"], "쉼표로 이은 값은 공백 하나로 구분됩니다."),
  O("print('a' * 2 + 'b')", "print('a' * 2 + 'b')", "aab", ["abab", "a2b", "aabb"], "곱셈이 덧셈보다 먼저 계산됩니다. 'aa' + 'b' 입니다."),
  O("print(1, 2, 3, sep=', ')", "print(1, 2, 3, sep=', ')", "1, 2, 3", ["1 2 3", "1,2,3", "123"], "sep 값이 각 항목 사이에 들어갑니다."),
  O("print('Hi', end='!')", "print('Hi', end='!'); print('Yo')", "Hi!Yo", ["Hi! Yo", "Hi Yo", "HiYo"], "end로 줄바꿈 대신 다른 문자를 붙일 수 있습니다."),
  O("print(f'{3 + 4}')", "print(f'{3 + 4}')", "7", ["{3 + 4}", "3 + 4", "f7"], "f-string의 중괄호 안 식은 계산되어 들어갑니다."),
  O("print('%d + %d' % (1, 2))", "print('%d + %d' % (1, 2))", "1 + 2", ["3", "1 + 2 = 3", "%d + %d"], "%d 자리에 튜플의 값이 차례로 들어갑니다."),
  O("print(\"It's\")", "print(\"It's\")", "It's", ["\"It's\"", "Its", "오류"], "큰따옴표로 감싸면 안에 작은따옴표를 쓸 수 있습니다."),
  E("print('Hi', 'there')", "print('Hi'", ["print('Hi')", "print('Hi', 'a')", "print('Hi' 'a')"], "괄호를 닫지 않으면 SyntaxError가 납니다."),
  O("print(5 > 3)", "print(5 > 3)", "True", ["true", "5 > 3", "1"], "비교 결과는 True 또는 False로 출력됩니다."),
  O("print(round(3.14159, 2))", "print(round(3.14159, 2))", "3.14", ["3.1", "3.15", "3"], "round(값, 2)는 소수 둘째 자리까지 반올림합니다."),
 ],
 "circle": [
  O("print(*[1, 2, 3])", "print(*[1, 2, 3])", "1 2 3", ["[1, 2, 3]", "123", "1, 2, 3"], "*를 붙이면 리스트가 펼쳐져 값마다 따로 전달됩니다."),
  O("print('-' * 10)", "print('-' * 10)", "----------", ["- * 10", "-----", "-10"], "'-'를 10번 반복한 문자열이 출력됩니다."),
  O("print(1, 2, sep='+', end='=')", "print(1, 2, sep='+', end='='); print(3)", "1+2=3", ["1 2 3", "1+2 =3", "1+2 3"], "sep은 값 사이, end는 출력 끝에 붙습니다."),
  O("print(f'{3.14159:.2f}')", "print(f'{3.14159:.2f}')", "3.14", ["3.14159", "3.1", "3.142"], ":.2f 는 소수 둘째 자리까지 표시합니다."),
  O("print('{} is {}'.format('A', 1))", "print('{} is {}'.format('A', 1))", "A is 1", ["{} is {}", "A is {}", "1 is A"], "format의 값이 {} 자리에 차례로 들어갑니다."),
  O("print(f'{7:03d}')", "print(f'{7:03d}')", "007", ["7", "070", "700"], "03d는 3자리로 맞추고 앞을 0으로 채웁니다."),
  O("print(str(1) + str(2))", "print(str(1) + str(2))", "12", ["3", "1 2", "오류"], "문자열로 바꾼 뒤 + 하면 이어 붙입니다."),
  O("print('a' 'b')", "print('a' 'b')", "ab", ["a b", "오류", "a, b"], "나란히 쓴 문자열 리터럴은 자동으로 이어집니다."),
  O("print(f'{10:b}')", "print(f'{10:b}')", "1010", ["10", "A", "12"], ":b 는 2진수로 바꿔 표시합니다."),
  O("print(*'abc', sep='-')", "print(*'abc', sep='-')", "a-b-c", ["abc", "a b c", "-a-b-c"], "문자열을 펼친 뒤 sep로 이어 출력합니다."),
 ],
}

변수 = {
 "square": [
  O("x = 10", "x = 10; print(x)", "10", ["x", "'10'", "오류"], "변수 x에 10이 저장되어 print(x)는 10을 출력합니다."),
  O("name = 'Kim'", "name = 'Kim'; print(name)", "Kim", ["name", "'Kim'", "오류"], "변수를 출력하면 저장된 값이 나옵니다."),
  O("a = b = 5", "a = b = 5; print(a + b)", "10", ["5", "55", "오류"], "a와 b에 모두 5가 저장됩니다."),
  O("count = 0", "count = 0; count = count + 1; print(count)", "1", ["0", "2", "오류"], "기존 값에 1을 더해 다시 저장합니다."),
  O("x, y = 1, 2", "x, y = 1, 2; print(y)", "2", ["1", "12", "(1, 2)"], "한 줄에 여러 변수를 동시에 대입할 수 있습니다."),
  F("x = 3", "빈칸에 들어갈 기호는? x ___ 3  (변수 x에 3을 저장)", "=", ["==", "!=", ":"], "= 는 값을 저장하는 대입 연산자입니다."),
  E("age = 15", "1age = 15", ["age = 15", "age1 = 15", "_age = 15"], "변수 이름은 숫자로 시작할 수 없습니다."),
  O("price = 1200", "price = 1200; price = 1500; print(price)", "1500", ["1200", "2700", "오류"], "나중에 저장한 값이 이전 값을 덮어씁니다."),
  O("pi = 3.14", "pi = 3.14; print(type(pi))", "<class 'float'>", ["<class 'int'>", "<class 'str'>", "<class 'double'>"], "소수는 float 자료형입니다."),
  O("b = a", "a = 1; b = a; a = 2; print(b)", "1", ["2", "3", "오류"], "b에는 대입 시점의 값 1이 저장됩니다."),
 ],
 "pyramid": [
  O("x = x + 1", "x = 5; x = x + 1; print(x)", "6", ["5", "x + 1", "오류"], "현재 값에 1을 더해 다시 x에 저장합니다."),
  O("x += 2", "x = 5; x += 2; print(x)", "7", ["5", "52", "오류"], "+= 는 더한 값을 다시 저장합니다."),
  O("a, b = b, a", "a, b = 1, 2; a, b = b, a; print(a, b)", "2 1", ["1 2", "2 2", "1 1"], "튜플 대입으로 두 값을 서로 바꿉니다."),
  E("my_name = 'Lee'", "my-name = 'Lee'", ["my_name = 'Lee'", "myName = 'Lee'", "name2 = 'Lee'"], "변수 이름에 - 는 쓸 수 없고 _ 를 씁니다."),
  O("total = 10 + 5", "total = 10 + 5; print(total)", "15", ["10 + 5", "105", "오류"], "오른쪽 식을 계산한 결과가 저장됩니다."),
  O("x = y = 0", "x = y = 0; y = 3; print(x, y)", "0 3", ["3 3", "0 0", "3 0"], "y를 바꿔도 x는 그대로입니다."),
  O("s = 'ab' * 2", "s = 'ab' * 2; print(s)", "abab", ["ab2", "abb", "4"], "문자열 곱셈은 반복입니다."),
  E("class_name = 'A'", "class = 'A'", ["class_ = 'A'", "cls = 'A'", "klass = 'A'"], "class는 예약어라 변수 이름으로 쓸 수 없습니다."),
  O("n = int('7')", "n = int('7'); print(n + 1)", "8", ["71", "'8'", "오류"], "int('7')은 정수 7이므로 더하면 8입니다."),
  O("x = None", "x = None; print(x)", "None", ["0", "''", "null"], "None은 값이 없음을 나타냅니다."),
 ],
 "circle": [
  O("a = b = c = 1", "a = b = c = 1; b = 2; print(a + b + c)", "4", ["3", "6", "5"], "b만 2로 바뀌므로 1 + 2 + 1 = 4입니다."),
  O("x, *y = 1, 2, 3", "x, *y = 1, 2, 3; print(y)", "[2, 3]", ["2", "[1, 2]", "(2, 3)"], "*y는 남은 값을 리스트로 받습니다."),
  O("x = (y := 3) + 1", "x = (y := 3) + 1; print(x, y)", "4 3", ["3 4", "4 4", "3 3"], ":= 는 값을 저장하면서 그 값을 돌려줍니다."),
  O("n //= 3", "n = 10; n //= 3; print(n)", "3", ["3.33", "4", "1"], "//= 는 몫으로 갱신합니다."),
  O("b = a; b.append(2)", "a = [1]; b = a; b.append(2); print(a)", "[1, 2]", ["[1]", "[2]", "[1, 2, 2]"], "리스트는 같은 객체를 가리켜서 b의 변경이 a에도 보입니다."),
  O("x **= 2", "x = 5; x **= 2; print(x)", "25", ["10", "7", "52"], "**= 는 거듭제곱 후 저장합니다."),
  O("a *= 3", "a = 'x'; a *= 3; print(a)", "xxx", ["x3", "x x x", "오류"], "문자열도 *= 로 반복할 수 있습니다."),
  O("first, second = 'ab'", "first, second = 'ab'; print(second)", "b", ["a", "ab", "오류"], "문자열도 글자 단위로 풀어 대입할 수 있습니다."),
  O("b = a + 1", "a = 1; b = a + 1; a = 5; print(b)", "2", ["6", "5", "1"], "b는 계산 시점의 값 2를 유지합니다."),
  O("v = 3 if True else 4", "v = 3 if True else 4; print(v)", "3", ["4", "True", "오류"], "조건이 참이면 앞의 값이 저장됩니다."),
 ],
}

입력 = {
 "square": [
  F("input()", "사용자가 키보드로 입력한 글자를 받는 함수는?", "input()", ["print()", "read()", "scan()"], "입력은 input() 함수로 받습니다."),
  O("name = input()", "name = input(); print(name)", "Kim", ["name", "input", "오류"], "입력값이 변수에 저장되어 출력됩니다.", stdin="Kim"),
  O("age = input()", "age = input(); print(type(age))", "<class 'str'>", ["<class 'int'>", "15", "<class 'float'>"], "input()은 항상 문자열을 돌려줍니다.", stdin="15"),
  O("n = int(input())", "n = int(input()); print(n + 1)", "5", ["41", "4", "오류"], "int()로 바꾸면 숫자 계산이 됩니다.", stdin="4"),
  F("input('Name: ')", "input('Name: ') 에서 'Name: ' 은 입력 전에 화면에 보이는 ____ 문구이다.", "안내", ["오류", "결과", "변수"], "괄호 안 문자열은 입력 안내 문구로 표시됩니다."),
  O("x = input()", "x = input(); print(x * 2)", "33", ["6", "3 3", "오류"], "문자열 '3'을 2번 반복하면 '33'입니다.", stdin="3"),
  O("a = int(input())", "a = int(input()); print(a * 2)", "8", ["44", "4", "오류"], "정수로 바꾼 뒤 2를 곱합니다.", stdin="4"),
  F("msg = input()", "빈칸에 들어갈 함수는? msg = ____()  (키보드 입력 받기)", "input", ["print", "int", "str"], "input()으로 입력을 받습니다."),
  O("num = float(input())", "num = float(input()); print(num)", "2.0", ["2", "'2'", "오류"], "float()는 소수 형태의 실수로 바꿉니다.", stdin="2"),
  F("y = input('? ')", "y = input('? ') 에서 y에 저장되는 값은 사용자가 입력한 ____ 이다.", "문자열", ["숫자", "안내 문구", "오류"], "input()은 숫자를 입력해도 문자열로 저장합니다."),
 ],
 "pyramid": [
  O("a, b = input().split()", "a, b = input().split(); print(b)", "y", ["x", "x y", "오류"], "split()은 공백으로 나눠 값을 두 변수에 나눠 담습니다.", stdin="x y"),
  O("n = int(input()) * 2", "n = int(input()) * 2; print(n)", "6", ["33", "3", "오류"], "정수로 바꾼 값에 2를 곱합니다.", stdin="3"),
  O("s = input().upper()", "s = input().upper(); print(s)", "ABC", ["abc", "Abc", "오류"], "upper()는 대문자로 바꿉니다.", stdin="abc"),
  F("name = input('Name: ')", "input()이 돌려주는 값의 자료형은 항상 ____ 이다.", "str", ["int", "float", "bool"], "입력값은 항상 str입니다."),
  O("x = input().strip()", "x = input().strip(); print(len(x))", "2", ["5", "3", "4"], "strip()은 앞뒤 공백을 지웁니다.", stdin="  hi "),
  O("a = int(input()) + int(input())", "a = int(input()) + int(input()); print(a)", "5", ["23", "2", "6"], "두 입력을 각각 정수로 바꿔 더합니다.", stdin="2\n3"),
  F("v = input().lower()", "대문자를 소문자로 바꾸는 문자열 메서드는?", "lower()", ["small()", "down()", "lowercase()"], "lower()는 소문자로 바꿉니다."),
  O("nums = input().split()", "nums = input().split(); print(len(nums))", "3", ["1", "5", "123"], "공백으로 나눈 조각 개수는 3개입니다.", stdin="1 2 3"),
  E("r = int(input())", "int(input() + 1)", ["int(input()) + 1", "int(input())", "str(int(input()) + 1)"], "input() + 1 은 문자열과 숫자를 더하려 해서 TypeError가 납니다."),
  O("p = float(input())", "p = float(input()); print(p * 2)", "3.0", ["3", "1.51.5", "오류"], "실수에 2를 곱하면 3.0입니다.", stdin="1.5"),
 ],
 "circle": [
  O("x, y = map(int, input().split())", "x, y = map(int, input().split()); print(x + y)", "7", ["34", "3 4", "오류"], "map(int, ...)로 각 값을 정수로 바꿉니다.", stdin="3 4"),
  O("nums = list(map(int, input().split()))", "nums = list(map(int, input().split())); print(sum(nums))", "6", ["123", "3", "오류"], "정수 리스트로 만든 뒤 합계를 구합니다.", stdin="1 2 3"),
  F("n = int(input('N: '))", "빈칸에 들어갈 함수는? n = ____(input())  (입력을 정수로 바꾸기)", "int", ["str", "float", "num"], "int()가 문자열을 정수로 바꿉니다."),
  O("a = input().split(',')", "a = input().split(','); print(a)", "['a', 'b', 'c']", ["a b c", "['a,b,c']", "a,b,c"], "쉼표를 기준으로 나눈 리스트가 됩니다.", stdin="a,b,c"),
  O("t = input() * 2", "t = input() * 2; print(t)", "abab", ["ab2", "abb", "오류"], "문자열 입력을 2번 반복합니다.", stdin="ab"),
  O("k = int(input()) // 2", "k = int(input()) // 2; print(k)", "3", ["3.5", "4", "14"], "7 // 2 의 몫은 3입니다.", stdin="7"),
  O("s = input()[::-1]", "s = input()[::-1]; print(s)", "cba", ["abc", "bca", "acb"], "[::-1]은 문자열을 뒤집습니다.", stdin="abc"),
  O("w = input().split()[0]", "w = input().split()[0]; print(w)", "hi", ["there", "hi there", "h"], "나눈 조각 중 첫 번째를 고릅니다.", stdin="hi there"),
  O("c = input().count('a')", "c = input().count('a'); print(c)", "3", ["2", "6", "1"], "banana에는 a가 3개 있습니다.", stdin="banana"),
  O("m = int(input()) % 2", "m = int(input()) % 2; print(m)", "1", ["0", "4", "9"], "9를 2로 나눈 나머지는 1입니다.", stdin="9"),
 ],
}
